default: &default
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock
  adapter: mysql2
  encoding:  utf8mb4
  charset:   utf8mb4
  collation: utf8mb4_general_ci
  pool: 5

development:
  <<: *default
  database: mywiki_development

test:
  <<: *default

production:
  <<: *default
