# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ebe8e5a903cdb08118b653924f9a5bb23385b01ba6901f51b0fa7b84d8da898cd15b72ead67f0894a761230e44bf0c11f894ab78eb37dc01519ff7140fd240

test:
  secret_key_base: eb26c222d78e0928a1bac4edf015ecdbe2527a8e5f5376b84f478cd4aa52fa694e130fae531895f9b7d7b839350e4a5bd83fa5f939d75a87387ae9e94750e32d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
